# Generated by Django 4.0.4 on 2022-06-05 09:49

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('distance', models.FloatField(default=0)),
                ('title', models.CharField(default='Trax Activity', max_length=25)),
                ('description', models.CharField(default='', max_length=1000)),
                ('gpx_file', cloudinary.models.CloudinaryField(default='manual', max_length=255, verbose_name='')),
                ('likes', models.ManyToManyField(blank=True, related_name='activity_like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
