# Generated by Django 4.0.4 on 2022-06-06 14:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='gpx_thumbnail',
            field=cloudinary.models.CloudinaryField(default='tumbnail_default.png', max_length=255, verbose_name=''),
        ),
    ]
