# Generated by Django 4.0.4 on 2022-06-04 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_activity_description_activity_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='activity_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
