# Generated by Django 4.0.4 on 2022-06-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_activity_gpx_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='gpx_thumb_path',
            field=models.CharField(default='https://res.cloudinary.com/dapgpdd7z/image/upload/v1654524799/thumbnail_default_oxyqoe.png', max_length=1000),
        ),
    ]
