# Generated by Django 4.0.4 on 2022-06-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_activity_gpx_thumb_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='heartrate_avg',
            field=models.FloatField(default=0),
        ),
    ]
