# Generated by Django 4.0.4 on 2022-06-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_activity_date_created_alter_activity_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='elev_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='elev_min',
            field=models.FloatField(default=0),
        ),
    ]
