# Generated by Django 4.0.6 on 2022-10-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_activity_gpx_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='gpx_file_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
